version: '3'
services:
  redis:
    image: ubuntu/redis:latest
    container_name: redis
    environment:
      TZ: Asia/Tokyo
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    networks:
      - backend
    ports:
      - 6379:6379
    restart: always

  iinfer:
    image: hamacom/iinfer:${VERSION}
    container_name: iinfer
    environment:
      TZ: Asia/Tokyo
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    networks:
      - backend
    user: ${USER}
    restart: always
    working_dir: /home/${USER}
    volumes:
      - ~/:/home/${USER}/

networks:
  backend:
    driver: bridge
