version: '3'
services:
  redis:
    image: ubuntu/redis:latest
    container_name: redis
    environment:
      TZ: Asia/Tokyo
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    networks:
      - backend
    ports:
      - 6379:6379
    restart: always

networks:
  backend:
    driver: bridge
